server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

orkestra:
  aws:
    region: us-east-1
    local: true
    accessKey: test
    secretKey: test
  dynamodb:
    endpoint: http://localhost:4566
